### ISSUE TITLE
Crash if MQTTSession stream is created and disposed of quickly

### ISSUE THREAD

**Issue by paulw11** [aciidb0mb3r/SwiftMQTT#33] opened 2018-08-28 02:29 UTC
I was getting a crash in SwiftMQTT if there was a short period between the creation and dispose of an `MQTTSessionStream` - the problem is that the `[weak self]` has been released before the async block executes on the `sessionQueue`.  The following check addresses the issue:

sessionQueue.async { [weak self] in
			if self != nil {
				let currentRunLoop = RunLoop.current
				inputStream?.schedule(in: currentRunLoop, forMode: .defaultRunLoopMode)
				outputStream?.schedule(in: currentRunLoop, forMode: .defaultRunLoopMode)
				inputStream?.open()
				outputStream?.open()
				if ssl {
					let securityLevel = StreamSocketSecurityLevel.negotiatedSSL.rawValue
					inputStream?.setProperty(securityLevel, forKey: .socketSecurityLevelKey)
					outputStream?.setProperty(securityLevel, forKey: .socketSecurityLevelKey)
				}
				if timeout > 0 {
					DispatchQueue.global().asyncAfter(deadline: .now() +  timeout) {
						self?.connectTimeout()
					}
				}
				
				currentRunLoop.run()
			}
		}
	}

**Comment by paulw11** [comment] 2018-08-28 02:30
Actually this code doesn't fix it :(

**Comment by adolfo** [comment] 2018-08-28 04:53
@paulw11 could you write a failing test that reproduces this issue? A PR that fixes the problem is also appreciated if you find the solution.

**Comment by adolfo** [comment] 2019-04-11 21:55
Resolved in #40

**Closed by adolfo** 2019-04-11 21:55 UTC
